package pl.mc.battleships.common;

/**
 * @author mc
 * Enum for generating the dummy board for View class.
 */
public enum ShipType {
  //empty field
  EMPTY, 
  
  //1 mast ships
  PATROL_BOAT, PATROL_BOAT_SUNKEN,
  
  //2 mast ships
  CRUISER_VERTICAL, CRUISER_HORIZONTAL,
  CRUISER_VERTICAL_SUNKEN, CRUISER_HORIZONTAL_SUNKEN,
  
  //3 mast ships
  SUBMARINE_VERTICAL, SUBMARINE_HORIZONTAL,
  SUBMARINE_VERTICAL_SUNKEN, SUBMARINE_HORIZONTAL_SUNKEN,
  
  //4 mast ships
  BATTLESHIP_VERTICAL, BATTLESHIP_HORIZONTAL,
  BATTLESHIP_VERTICAL_SUNKEN, BATTLESHIP_HORIZONTAL_SUNKEN,
  
  //5 mast ships
  AIRCRAFT_CARRIER_VERTICAL, AIRCRAFT_CARRIER_HORIZONTAL,
  AIRCRAFT_CARRIER_VERTICAL_SUNKEN, AIRCRAFT_CARRIER_HORIZONTAL_SUNKEN
}
